### ISSUE TITLE
Language not work

### ISSUE THREAD

**Issue by ghost** [prateekmedia/appimagepool#64]
Hi!, language not work only show english, but can´t change to spanish for example, how is possible edit the app for add a flag selector¿?

**Comment by prateekmedia** [comment]
Set your system level language to spanish for that.

**Comment by prateekmedia** [comment]
Ok I will try to add an option for language selection

**Comment by JavierGallego** [comment]
is possible have the source code for try to make the changes?

**Comment by Bira-oliverio** [comment]
The app displays in Arabic (I think) but my system is set for brazilian portuguese. In fact is not only the text, url all screen controls are using the Arabic format. See the attachements.
![App _in_Arabic](https://user-images.githubusercontent.com/25584338/171998361-3dba2b5b-40d3-4415-aba7-4ecec76bf20f.png)
![System_settings](https://user-images.githubusercontent.com/25584338/171998408-3a51c83c-53e5-42c2-966d-f83f59bab8ec.png)

**Comment by g3434343** [comment]
> The app displays in Arabic (I think), but my system is set for brazilian portuguese. In fact is not only the text, all screen controls are using the Arabic format. See the attachements. ![App _in_Arabic](https://user-images.githubusercontent.com/25584338/171998361-3dba2b5b-40d3-4415-aba7-4ecec76bf20f.png) ![System_settings](https://user-images.githubusercontent.com/25584338/171998408-3a51c83c-53e5-42c2-966d-f83f59bab8ec.png)

Same for me.

**Comment by Master811129** [comment]
![Screenshot_20220727_121430](https://user-images.githubusercontent.com/37829730/181191051-f306219f-0a3a-489f-a883-2f06c4f368ba.png)
My PC is on English but this app shows in Arabic. there is no settings to set the language

**Comment by prateekmedia** [comment]
Already fixed in Nightly version(available in README)

**Comment by Romain-Revel** [comment]
Hi,
I tried your both your AppImage and tar.
Both run with Arabic language...
Moreover, I didn't find any parameter to modifiy it in-app.

It seems you did NOT fix this.

I am running Linux Mint 21 x86_64.

**Comment by prateekmedia** [comment]
@Romain-Revel Could you try the nightly appimage from README?

**Comment by sushidave** [comment]
@prateekmedia 
Hi, 
I learned about your app on https://itsfoss.com/appimagepool/, noticed the same thing with the default language (Arabic) and found this issue. The nightly appimage solved it for me.
Thanks very much!

**Comment by prateekmedia** [comment]
Fixed in v5,1,0
